### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by dag** [dag/jbo#8]
Candidates: BSD, MIT, Apache2, LGPL

BSD: Different clauses confusing
MIT: How does it differ from BSD?
Apache2: How does it differ from BSD/MIT?
LGPL: What does it really mean?

Public Domain: Consider dual license where legally meaningful. What does the lack of any disclaimer in PD mean practically?

**Comment by alanpost** [comment]
FWIW, the Apache2 license is not acceptable to the OpenBSD team, though the reason is unclear or unstated.  (http://www.undeadly.org/cgi?action=article&sid=20040220085910)

Apache2 seems to be incompatible with GPL2, but not with GPL3.  (http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)

**Comment by alanpost** [comment]
Here is a discussion on the difference between Apache, MIT, and BSD licenses:

http://stackoverflow.com/questions/40100/apache-licence-vs-bsd-vs-mit

**Comment by dag** [comment]
Thank you.

BSD: Obviously the four-clause version is out of the question; I don't really care for the non-endorsement clause in the three-clause version nor the added disclaimer in the two-clause version. The two-clause version without the added disclaimer, as used in NetBSD, is a possibility but generally BSD licenses seem too confusing.

MIT/X11: Basically the two-clause BSD without the added disclaimer, so an obvious candidate. Does not require the disclaimer to be included in derivatives - bad?

ISC: Even simpler version of MIT/X11, which I think is a good thing. Preferred by OpenBSD. Does not either require the disclaimer to be included and is more vague than MIT/X11 on what a derivative is - just says "copies" where MIT/X11 says "copies or substantial portions of the Software".

I'll review Apache2 and LGPL later.

**Comment by dag** [comment]
License as Simplified BSD, add package classifiers, closed by eba61f9a2b57639d408eb5842eaef2bb4534f861
